import type { Metadata } from "next";
import "./globals.css";
import NAV from './nav/page'
import Footer from './footer/page'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div style={{ display: "flex", flexDirection: "column", minHeight: "85vh" }}>
      {/* Navbar at Top */}
      <NAV />

      {/* Main Content in Center */}
      <main style={{ flexGrow: 1, display: "flex", justifyContent: "center", alignItems: "center", padding: "20px" }}>
        {children}
      </main>
      {/* Footer at Bottom */}
      <Footer />
    </div>
      </body>
    </html>
  );
}
